  name         : project
  description  : Template for translating projects to RDF

  type:  Composite
  bind: 
    $base: http://data.sedgemoor.gov.uk/id/
  
  prefixes: 
    rdf        : http://www.w3.org/1999/02/22-rdf-syntax-ns#
    rdfs       : http://www.w3.org/2000/01/rdf-schema#
    owl        : http://www.w3.org/2002/07/owl#
    dcterms    : http://purl.org/dc/terms/
    geo-sparql : http://www.opengis.net/def/geosparql/
    geo        : http://www.w3.org/2003/01/geo/wgs84_pos#
    xsd        : http://www.w3.org/2001/XMLSchema#
    impact    : http://data.sedgemoor.gov.uk/def/impact/
    project    : http://data.sedgemoor.gov.uk/def/project/
    wdrs       : http://www.w3.org/2007/05/powder-s#
    
  templates : 
   - name                       : project
     "@id"                      : <{$base}{identifier}>
     <rdf:type>                 : <project:Project>
     <rdfs:label>               : "{name}@en"
     <dcterms:description>      : "{description}@en"
     <wdrs:describedBy>         : |
       <{ { 
         if ( reference != null) {
           if (reference_section == null) {
             if (reference_version == null) {
                 return $base.value.concat(reference.value.toString())
             } else {
               return $base.value.concat(reference.value.toString()).concat('/ver/').concat(reference_version.value.toString())
             }
           } else {
             return $row.bnode ;
           }
         }
       } }>
     <project:operatesOn>       : <{$base}{about}>
     <project:proposal>         : <{$base}{proposal}>
     <impact:mitigates>         : <{$base}{mitigates}>
     <project:hasParentProject> : <{$base}{parent_project}>
     ^<project:hasSubProject>   : <{$base}{parent_project}>
     <project:expectedStart>    : "{expected_start}"
     <project:expectedEnd>      : "{expected_end}"
     <project:actualStart>      : "{actual_start}"
     <project:actualEnd>        : "{actual_end}"
     <project:resourcedBy>      : <{$base}{resourced_by}>
     ^<project:resources>       : <{$base}{resourced_by}>
     <project:resources>        : <{$base}{resources}>
     <owl:sameAs>               : <{same_as}>
     
   - name                  : sameAs
     "@id"                 : <{same_as}>
     <rdfs:label>          : "{same_as_name}"    
     
   - name                       : reference
     "@id"                      : |
       <{ {
         if (reference_section != null) {
           return $row.bnode ;
         } else {
           return null
         }
       } }>
     <dcterms:isPartOf>         :  |
       <{ {
             if (reference_version == null) {
                 return $base.value.concat(reference.value.toString())
             } else {
               return $base.value.concat(reference.value.toString()).concat('/ver/').concat(reference_version.value.toString())
             }
       } }>
     <dcterms:identifier>       : "{reference_section}"
     
     

